import softwareDevelopment from "../../../../../assets/marketplaceImages/software-development.png";
import cloudDevOps from "../../../../../assets/marketplaceImages/cloud-devops.png";
import aiData from "../../../../../assets/marketplaceImages/ai-data.png";
import testing from "../../../../../assets/marketplaceImages/testing.png";
import career from "../../../../../assets/marketplaceImages/career.png";

import reactFullStack from "../../../../../assets/cardImages/MERNstack1.png";
import pythonFullStack from "../../../../../assets/cardImages/pythonFullStack.png";
import javaFullStack from "../../../../../assets/cardImages/javaFullStack.png";
import mernStack from "../../../../../assets/cardImages/MERNstack1.png";


export const courses = [
  {
    id: "REACT-FS",
    category: "Software Development",
    level: "Intermediate",
    title: "Full Stack Development",
    instructor: "Arjun Mehta",
    initials: "AM",
    duration: "14 weeks",
    lessons: "96 lessons",
    tag1: "Live cohort",
    tag2: "Coding labs",
    price: "₹5,499",
    oldPrice: "₹8,999",
    students: "1,240 students",
    image: reactFullStack,
  },

  {
    id: "PY-FS",
    category: "Software Development",
    level: "Beginner",
    title: "Python Full Stack",
    instructor: "Sowmya Iyer",
    initials: "SI",
    duration: "16 weeks",
    lessons: "112 lessons",
    tag1: "Hybrid",
    tag2: "Placement-linked",
    price: "₹6,499",
    oldPrice: "₹9,999",
    students: "2,100 students",
    image: pythonFullStack,
  },

  {
    id: "JAVA-FS",
    category: "Software Development",
    level: "Intermediate",
    title: "Java Full Stack Development",
    instructor: "Naveen Kulkarni",
    initials: "NK",
    duration: "18 weeks",
    lessons: "128 lessons",
    tag1: "Classroom",
    tag2: "Placement-linked",
    price: "₹6,999",
    oldPrice: "₹11,999",
    students: "1,850 students",
    image: javaFullStack,
  },

  {
    id: "AWS-DOP",
    category: "Cloud & DevOps",
    level: "Advanced",
    title: "AWS DevOps Engineer",
    instructor: "Meera Krishnan",
    initials: "MK",
    duration: "12 weeks",
    lessons: "74 lessons",
    tag1: "6 labs",
    tag2: "Proctored exam",
    price: "₹6,999",
    oldPrice: "₹10,999",
    students: "980 students",
    image: cloudDevOps,
  },

  {
    id: "K8S-PRD",
    category: "Cloud & DevOps",
    level: "Advanced",
    title: "Kubernetes for Production Workloads",
    instructor: "Meera Krishnan",
    initials: "MK",
    duration: "9 weeks",
    lessons: "52 lessons",
    tag1: "4 labs",
    tag2: "Production grade",
    price: "₹5,499",
    oldPrice: "₹8,499",
    students: "760 students",
    image: cloudDevOps,
  },

  {
    id: "DEVSEC",
    category: "Cloud & DevOps",
    level: "Intermediate",
    title: "Cloud Security & DevSecOps Essentials",
    instructor: "Tanvox Technologies",
    initials: "TT",
    duration: "8 weeks",
    lessons: "44 lessons",
    tag1: "Industry module",
    tag2: "Case studies",
    price: "₹5,299",
    oldPrice: "₹7,999",
    students: "640 students",
    image: cloudDevOps,
  },

  {
    id: "ML-PY",
    category: "AI & Data",
    level: "Intermediate",
    title: "Machine Learning with Python",
    instructor: "Dr. Anita Bose",
    initials: "AB",
    duration: "12 weeks",
    lessons: "62 lessons",
    tag1: "Live cohort",
    tag2: "Capstone",
    price: "₹7,499",
    oldPrice: "₹11,999",
    students: "2,100 students",
    image: aiData,
  },

  {
    id: "AGENTIC",
    category: "AI & Data",
    level: "Advanced",
    title: "Agentic AI Platform Engineering",
    instructor: "Rohit Sharma",
    initials: "RS",
    duration: "8 weeks",
    lessons: "46 lessons",
    tag1: "New Cohort",
    tag2: "Build agents",
    price: "₹8,999",
    oldPrice: "₹13,999",
    students: "520 students",
    image: aiData,
  },

  {
    id: "SQL-DM",
    category: "AI & Data",
    level: "Beginner",
    title: "SQL & Data Modelling for Engineers",
    instructor: "Dr. Anita Bose",
    initials: "AB",
    duration: "6 weeks",
    lessons: "38 lessons",
    tag1: "Self paced",
    tag2: "Practice set",
    price: "₹1,999",
    oldPrice: "₹3,499",
    students: "1,430 students",
    image: aiData,
  },

  {
    id: "SEL-AUT",
    category: "Testing",
    level: "Beginner",
    title: "Selenium Automation Testing",
    instructor: "Kavitha Reddy",
    initials: "KR",
    duration: "8 weeks",
    lessons: "54 lessons",
    tag1: "Placement-linked",
    tag2: "Framework",
    price: "₹3,499",
    oldPrice: "₹5,999",
    students: "1,520 students",
    image: testing,
  },

  {
    id: "API-PERF",
    category: "Testing",
    level: "Intermediate",
    title: "API & Performance Testing — Postman",
    instructor: "Kavitha Reddy",
    initials: "KR",
    duration: "5 weeks",
    lessons: "31 lessons",
    tag1: "Self paced",
    tag2: "Lab heavy",
    price: "₹2,999",
    students: "980 students",
    image: testing,
  },

  {
    id: "CAREER-01",
    category: "Career",
    level: "Beginner",
    title: "Interview Preparation & Resume Lab",
    instructor: "Placement Cell",
    initials: "PC",
    duration: "4 weeks",
    lessons: "22 lessons",
    tag1: "Free",
    tag2: "Mock interviews",
    price: "₹0",
    oldPrice: "₹0",
    students: "850 students",
    image: career,
  },

  {
    id: "CAREER-02",
    category: "Career",
    level: "Beginner",
    title: "Aptitude & Communication for Campus Hiring",
    instructor: "Placement Cell",
    initials: "PC",
    duration: "6 weeks",
    lessons: "40 lessons",
    tag1: "Free",
    tag2: "Campus ready",
    price: "₹0",
    oldPrice: "₹0",
    students: "1,120 students",
    image: career,
  },
];